### ISSUE TITLE
Magento 2 Error - "SQLSTATE[HY000] [2002] No such file or directory"

### ISSUE THREAD

**Issue by thadcb** [bryanlittlefield/TUGBOAT#8]
a:4:{i:0;s:48:"SQLSTATE[HY000] [2002] No such file or directory";i:1;s:4701:"#0 /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(353): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(861): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect()
#3 /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(931): Zend_Db_Adapter_Abstract->quote('1', NULL)
#4 /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(1378): Zend_Db_Adapter_Abstract->quoteInto('`store`.`store_...', '1', NULL, NULL)
#5 /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Select.php(1007): Magento\Framework\DB\Adapter\Pdo\Mysql->quoteInto('`store`.`store_...', '1', NULL)
#6 /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Select.php(477): Zend_Db_Select->_where('`store`.`store_...', '1', NULL, true)
#7 /var/www/html/vendor/magento/framework/DB/Select.php(120): Zend_Db_Select->where('`store`.`store_...', '1', NULL)
#8 /var/www/html/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(367): Magento\Framework\DB\Select->where('`store`.`store_...', '1')
#9 /var/www/html/vendor/magento/module-store/Model/ResourceModel/Store.php(182): Magento\Framework\Model\ResourceModel\Db\AbstractDb->_getLoadSelect('`store`.`store_...', '1', Object(Magento\Store\Model\Store\Interceptor))
#10 /var/www/html/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(341): Magento\Store\Model\ResourceModel\Store->_getLoadSelect('store_id', '1', Object(Magento\Store\Model\Store\Interceptor))
#11 /var/www/html/vendor/magento/framework/Model/AbstractModel.php(531): Magento\Framework\Model\ResourceModel\Db\AbstractDb->load(Object(Magento\Store\Model\Store\Interceptor), '1', 'store_id')
#12 /var/www/html/vendor/magento/module-store/Model/Store.php(488): Magento\Framework\Model\AbstractModel->load('1', NULL)
#13 /var/www/html/vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(181): Magento\Store\Model\Store->load('1')
#14 /var/www/html/vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(112): Magento\Store\App\Config\Source\RuntimeConfigSource->getStoresData('1')
#15 /var/www/html/vendor/magento/framework/App/Config/ConfigSourceAggregated.php(40): Magento\Store\App\Config\Source\RuntimeConfigSource->get('stores/1')
#16 /var/www/html/var/generation/Magento/Framework/App/Config/ConfigSourceAggregated/Proxy.php(95): Magento\Framework\App\Config\ConfigSourceAggregated->get('stores/1')
#17 /var/www/html/vendor/magento/module-store/App/Config/Type/Scopes.php(50): Magento\Framework\App\Config\ConfigSourceAggregated\Proxy->get('stores/1')
#18 /var/www/html/vendor/magento/framework/App/Config.php(139): Magento\Store\App\Config\Type\Scopes->get('stores/1')
#19 /var/www/html/vendor/magento/module-store/Model/StoreRepository.php(105): Magento\Framework\App\Config->get('scopes', 'stores/1', Array)
#20 /var/www/html/vendor/magento/module-store/Model/StoreRepository.php(124): Magento\Store\Model\StoreRepository->getById('1')
#21 /var/www/html/vendor/magento/module-store/Model/StoreResolver.php(167): Magento\Store\Model\StoreRepository->getActiveStoreById('1')
#22 /var/www/html/vendor/magento/module-store/Model/StoreResolver.php(105): Magento\Store\Model\StoreResolver->getDefaultStoreById('1')
#23 /var/www/html/vendor/magento/module-store/Model/StoreManager.php(154): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#24 /var/www/html/app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(80): Magento\Store\Model\StoreManager->getStore()
#25 /var/www/html/app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(28): Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->getCacheKey()
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(142): Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#28 /var/www/html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#30 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#31 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}

**Comment by thadcb** [comment]
User error. Disregard.
